# This file for sending repository webhook events to a Discord channel.
# Action: tsickert/discord-webhook@v7.0.0

name: Repository Webhook Events

on:
  create:
  delete:
  fork:
  issue_comment:
  issues:
  pull_request:
  push:
  release:
  watch:

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          EVENT_NAME: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          TIMESTAMP: ${{ github.event.head_commit.timestamp || github.event.comment.created_at || github.event.release.created_at || github.event.created_at || github.event.issue.created_at || github.event.pull_request.created_at }}
        run: |
          json_payload=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "A new \`$EVENT_NAME\` event occurred in the \`$REPOSITORY\` repository",
                "fields": [
                  {
                    "name": "Triggered by",
                    "value": "$ACTOR",
                    "inline": true
                  }
                ],
                "timestamp": "$TIMESTAMP"
              }
            ]
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$DISCORD_WEBHOOK_URL"