# This file for sending repository webhook events to a Discord channel.
# Action: tsickert/discord-webhook@v7.0.0

name: Repository Webhook Events

on:
  create:
  delete:
  fork:
  issue_comment:
  issues:
  pull_request:
  push:
  release:
  watch:

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification for Push Event
        if: github.event_name == 'push'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          commit_summary=$(echo '${{ toJSON(github.event.commits) }}' | jq -r '.[] | "[\`\(.id | .[:7])\`](\(.url)) \(.message)"' | sed 's/"/\\"/g' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')
          json_payload=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "[${{ github.repository }}] New commits to ${{ github.ref_name }}",
                "description": "${commit_summary}",
                "url": "${{ github.event.compare }}",
                "color": 3447003,
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://github.com/${{ github.actor }}.png"
                },
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            ]
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$DISCORD_WEBHOOK_URL"

      - name: Send notification for Other Events
        if: github.event_name != 'push'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          EVENT_NAME: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          TIMESTAMP: ${{ github.event.head_commit.timestamp || github.event.comment.created_at || github.event.release.created_at || github.event.created_at || github.event.issue.created_at || github.event.pull_request.created_at }}
        run: |
          json_payload=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "A new \`$EVENT_NAME\` event occurred in the \`$REPOSITORY\` repository",
                "fields": [
                  {
                    "name": "Triggered by",
                    "value": "$ACTOR",
                    "inline": true
                  }
                ],
                "timestamp": "$TIMESTAMP"
              }
            ]
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$json_payload" "$DISCORD_WEBHOOK_URL"